### ISSUE TITLE
Add TEST_ARGS to make test command

### ISSUE THREAD

**Issue by helenmasters** [AdoptOpenJDK/openjdk-systemtest#11]
Currently when running e.g. make test.JdiLoadTest I can't specify an individual test to run e.g. simple_launch.  To do that I have to go right down to the perl layer underneath. 

As I'm trying to investigate a failure in one test within the test suite adding this feature would make it easier to reproduce failures, as we could then allow the launching of single tests through jenkins directly.  In effect I'm requesting the addition of TEST_ARGS="test=basic_launch" or something similar to the makefile.

**Comment by lumpfish** [comment]
I'll add a test.Custom target in openjdk.build/makefile which one can then use as:
make test.Custom TEST=JdiTest TEST_ARGS="test=basic_launch" JAVA_ARGS="-Xint"
(TEST would be required, the other macros optional unless the TEST requires a -test-arg argument).

To enable execution on an AdoptOpenJDK test machine via Jenkins we will need a Jenkins job which allows a user to supply those macros via Parameters.

**Comment by helenmasters** [comment]
This is now merged and working, hence closing.

**Comment by lumpfish** [comment]
See https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/13 for enabling running the new test target on an AdoptOpenJDK test machine from Jenkins.
