### ISSUE TITLE
openjdk-systemtest build failing due to new antcontrib prereq

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-systemtest#111]
The openjdk-systemtest repo buil dis failing in the adtopopenjdk JCK runs with:

build:
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

build:

BUILD FAILED
/home/jenkins/workspace/JCK-fullrun-ppcle/git/openjdk-systemtest/openjdk.build/build.xml:54: The following error occurred while executing this line:
/home/jenkins/workspace/JCK-fullrun-ppcle/git/openjdk-systemtest/openjdk.test.modularity/build.xml:73: Problem: failed to create task or type if
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

The build was originally designed not to have a prereq on antcontrib (so that any would be used to get all the prereqs required by the build).  @Mesbah-Alam - what in the modularity tests has introduced the prereq?

**Comment by Mesbah-Alam** [comment]
openjdk.test.modularity/build.xml had a <for> to traverse through a list of native tests to build. Since we have only one native test, that for loop is not essential. In fact I had removed it from the script. I will remove the ant-contrib import from the script too.

**Comment by Mesbah-Alam** [comment]
Fixed via Fixed via https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/114
