### ISSUE TITLE
Determine java version used for compilation within build scripts

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-systemtest#117]
A JAVA_VERSION property is being used to determine whether certain test cases can be built (e.g. modularity test cases cannot be built if Java 8 is being used to build the repository).

JAVA_VERSION is required to be set by the user, but it could be determined quite easily by the build removing the need for the user to set it.  See https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/116 for details of how to do that.

**Comment by Mesbah-Alam** [comment]
Fixed via: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/119/files
