### ISSUE TITLE
Replace java8_xxx, java9_xxx properties by generic java_xxx properties in systemtest build script

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#118]
We are going to have a new Java release every 6 months from now. Hence, the strategy to use `java8_xxx` , `java9 _xxx` properties should be replaced with a generic `java_xxx` property set that can be used by all systemtest build scripts. If a test project needs a specific version of Java to build (i.e., modularity tests require Java 9 and up), we should handle that in the build script of that test project itself (we are doing it already in openjdk.test.modularity).  

Note from Simon: 
"If we duplicated the java8_xxxx peoperties as java_xxxx (no version), then that could be committed, and the the build scrripts could be switched over to use that one by one.  The when they're all done we could take out the java8_xxx and java9_xxx properties.  That way we should minimise the risk it all breaks. "

**Comment by lumpfish** [comment]
I'll start working on this.

**Comment by lumpfish** [comment]
Planning to make the changes incrementally.

This PR makes the change for the stf repository: https://github.com/AdoptOpenJDK/stf/pull/57
Test run at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/64/consoleFull

**Comment by Mesbah-Alam** [comment]
Started another test using Simon's `remove_multiple_javac_support` branch : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/68/console

**Comment by lumpfish** [comment]
Changes being made along with changes for https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/132

**Comment by Mesbah-Alam** [comment]
Fixed via https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/132
