### ISSUE TITLE
No makefile test targets for jlm and modularity tests

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-systemtest#120]
The openjdk.build/makefile does not have any targets to run the newly added jlm and modularity tests.

A user should be able to run
make help
and see targets which can be run to execute the tests in the repository (so make help needs to be updated as well as adding the targets themselves).

**Comment by Mesbah-Alam** [comment]
Pr for this issue: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/123

**Comment by Mesbah-Alam** [comment]
Related issue: https://github.com/eclipse/openj9-systemtest/issues/20

**Comment by lumpfish** [comment]
Running with the code committed in https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/123 I get an error
```
GEN 12:38:11.487 - ** ERROR **  Could not find test plugin called 'AutomaticModulesTest1' in any of these workspaces:
```
I think the issue is that that test is a variation of the generic test AutomaticModulesTest which requires the name of the test via a -test-args argument.

**Comment by Mesbah-Alam** [comment]
Yes, I missed that. I will fix it.

**Comment by Mesbah-Alam** [comment]
All related PRs seem to have been delivered for this issue. Closing it at this point.
