### ISSUE TITLE
Enable users to run system tests via Jenkins

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-systemtest#13]
This issue follows on from https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/11

In order to investigate a system test failure a user may want to rerun the test with additional debug options.  The user basically needs to execute a command on the test machine of the form
make test.Custom TEST=xxxx TEST_ARGS="xxxx" JAVA_ARGS="xxxx"
A Jenkins job with these Parameters:
1. The repository containing the test to be run (openjdk-systemtest / openj9-systemtest)
2. The value for TEST
3. The value for TEST_ARGS
4. The value for JAVA_ARGS
The job would then need to:
1. clone the system test repositories
2. Build the repositories
3. Run the
make test.Custom TEST=xxxx TEST_ARGS="xxxx" JAVA_ARGS="xxxx"
command line
4. Retrieve the test output for examination by the user

**Comment by sxa555** [comment]
initial prototype at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_stf_systemtests-user/

**Comment by sxa555** [comment]
initial prototype at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_stf_systemtests-user/

**Comment by sxa555** [comment]
Now also archives the /tmp/stf directory into a tgz that can be retrieved

**Comment by Mesbah-Alam** [comment]
@sxa555 - Do we still need this issue?

**Comment by smlambert** [comment]
See also: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/

**Comment by lumpfish** [comment]
The options provided via https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/build should satisfy this requirement.
