### ISSUE TITLE
JLM remote tests fail on openjdk8-j9 ppc64le_linux

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#145]
JLM remote tests fail consistently on openjdk8-j9 ppc64le_linux
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_ppc64le_linux/144/tapResults/

They pass on openjdk10-j9 ppc64le_linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_j9_systemtest_ppc64le_linux/54/tapResults/

They pass on openjdk9-j9 ppc64le linux: 
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_hs_systemtest_ppc64le_linux/120/tapResults/

They pass on the hotspot builds : 
SE10: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_ppc64le_linux/94/tapResults/

SE90: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_hs_systemtest_ppc64le_linux/120/tapResults/

We need to exclude this test from the failing platform and investigate if the failures point to genuine issues.

**Comment by lumpfish** [comment]
These tests are now passing due to the fix in https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/361
