### ISSUE TITLE
Require .jti files for JCK11+

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-systemtest#157]
https://github.com/AdoptOpenJDK/openjdk-systemtest/tree/master/openjdk.test.jck/config needs jck11 and onward jti files.  

If .jti files are common to each other, suggest creating a common dir for all versions to point to.

**Comment by suman-mitra** [comment]
@smlambert we are trying to create the jti fles for jck11.

**Comment by Mesbah-Alam** [comment]
Since JCK11 jti files have been made [available](https://github.com/Mesbah-Alam/openjdk-systemtest/tree/master/openjdk.test.jck/config/jck11), closing this issue at this point.
