### ISSUE TITLE
Add support for Arm

### ISSUE THREAD

**Issue by jabrena** [AdoptOpenJDK/openjdk-systemtest#160]
Hi,

Recently, I try to run a Jenkins job for software to run ARM and I think that maybe the test suite doesn't support it.

**Jenkins build output:**
https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk10_openjdktest_systemtest_ev3_linux/1/console

**Configuration:**

```
export BUILD_LIST=systemtest
export JAVA_BIN=/opt/jdktest/jdk/bin
export SPEC=linux-arm
export JAVA_VERSION=SE100
```

Error Message:

```
/opt/jdktest/openjdk-tests/TestConfig/scripts/build_test.xml:71: The following error occurred while executing this line:
/opt/jdktest/openjdk-tests/systemtest/build.xml:110: The following error occurred while executing this line:
/opt/jdktest/openjdk-tests/systemtest/openj9-systemtest/openj9.build/include/top.xml:193: The following error occurred while executing this line:
/opt/jdktest/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:66: The following error occurred while executing this line:
/opt/jdktest/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:503: The following error occurred while executing this line:
/opt/jdktest/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:600: java os.arch property value arm not recognised.  Update the get-platform-arch macrodef in openjdk.build/include/top.xml
Total time: 1 minute 38 seconds
makefile:82: recipe for target 'compile' failed
make: *** [compile] Error 1
```

The same configuration for the regression tests is running fine:

```
    export BUILD_LIST=openjdk_regression
    export JAVA_BIN=/opt/jdktest/jdk/bin
    export SPEC=linux-arm
    export JAVA_VERSION=SE100
```

Build example:
https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk10_openjdktest_ev3_linux/

**Comment by lumpfish** [comment]
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/include/top.xml

contains
```
<condition property="@{property}" value="arm">
	<and>
		<contains string="@{arch}" substring="aarch64"/>
	</and>
</condition>
```
which sets a property to 'arm' if java's os.arch property is set to aarch64.

In the case reported here java's os.arch property is set to arm, which is not expected - hence the 'not supported' message.  Not sure why that is.  Is 'arm' arm 32bit and aarch64 arm 64bit?

The solution is probably to set the property to arm for either value, since the code interrogates number of bits separately - so it differentiates between linux_arm-32 and linux_arm-64.

**Comment by Mesbah-Alam** [comment]
@lumpfish - you are right. System tests do look for a value of 'aarch64' for the property 'os.arch' in the environment. For example, on 'arm64' linux platform, `os.arch=aarch64` holds true, and system tests work fine: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk9_hs_systemtest_aarch64_linux/49/consoleFull   

However, in the build that's failing, we are using a 32 bit JRE (e.g. `java8.sun.arch.data.model=32`) , where, apparently, `os.arch=arm` - which is not recognized by systemtests. We need to add that variation.
