### ISSUE TITLE
LockingLoadTest fails on Linux aarch64 JDK11 hotspot

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#179]
**Test failure output**
```
 LLT testFailure: testCos(net.adoptopenjdk.test.math.MathAPITest): cos(double)[0] :: expected:<-0.9999876894265599> but was:<-0.99998768942656>
LLT junit.framework.AssertionFailedError: cos(double)[0] :: expected:<-0.9999876894265599> but was:<-0.99998768942656>
LLT 	at junit.framework.Assert.fail(Assert.java:57)
LLT 	at junit.framework.Assert.failNotEquals(Assert.java:329)
LLT 	at junit.framework.Assert.assertEquals(Assert.java:78)
LLT 	at junit.framework.TestCase.assertEquals(TestCase.java:244)
LLT 	at net.adoptopenjdk.test.math.MathAPITest.testCos(MathAPITest.java:366)
...
```

```
 testFailure: testLog(net.adoptopenjdk.test.math.MathAPITest): log(double)[2] :: expected:<-744.4400719213812> but was:<-710.989276736877>
LLT junit.framework.AssertionFailedError: log(double)[2] :: expected:<-744.4400719213812> but was:<-710.989276736877>
LLT 	at junit.framework.Assert.fail(Assert.java:57)
LLT 	at junit.framework.Assert.failNotEquals(Assert.java:329)
LLT 	at junit.framework.Assert.assertEquals(Assert.java:78)
LLT 	at junit.framework.TestCase.assertEquals(TestCase.java:244)
LLT 	at net.adoptopenjdk.test.math.MathAPITest.testLog(MathAPITest.java:813)
...
```

**Test repo:** 
https://github.com/AdoptOpenJDK/openjdk-systemtest

**Build link**
https://ci.adoptopenjdk.net/job/openjdk11_hs_systemtest_aarch64_linux/1/tapResults/

* Note, the same test passes on other platforms (e.g. Linux x64: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_x86-64_linux/16/tapResults/)

**Comment by Mesbah-Alam** [comment]
Grinder link: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/203/console

**Comment by Mesbah-Alam** [comment]
@karianna - this looks to be an issue in hotspot aarch64 Linux build. Could someone take a look at it?

**Comment by karianna** [comment]
Pretty sure this is the know P1 bug that's been put into 11u.  I've got an open issue assigned to myself (https://github.com/AdoptOpenJDK/openjdk-jdk11/issues/2) to port that to our openjdk-jdk11 repo.  Let me see if I cna do that quickly now.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-jdk11/pull/3

**Comment by stooart-mon** [comment]
Doing A/B testing on those particular cases shows that it is fixed by AdoptOpenJDK/openjdk-jdk11#3 / 2 .
You were correct to be sure.

**Comment by Mesbah-Alam** [comment]
Started gridner to verify that the test works with the latest AdoptOpenJDK aarch64 sdk: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/218/console

**Comment by Mesbah-Alam** [comment]
The test passed 5x grinder with latest jdk11 hotspot build. I'll include the test back into the build: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/248/tapResults/

**Comment by Mesbah-Alam** [comment]
Test being included back to build: https://github.com/AdoptOpenJDK/openjdk-tests/pull/619
