### ISSUE TITLE
JCK automation does not seem to specify a path to an OpenJDK reference VM implementation

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-systemtest#18]
From the JCK User's Guide:
It is important to note how the JCK compiler tests work. RMI compilers and the
Java programming language compiler (Java compiler) compile test files and the
resulting class files are executed on a Oracle reference runtime implementation.

The "reference VM" is to verify the "byte codes" produced by the javac compiler are the ones expected by a reference implementation for obvious portability reasons.

I do not see where the "reference VM" is specified in the JCK automation?

**Comment by lumpfish** [comment]
Discussion moved to private repository.

**Comment by lumpfish** [comment]
Closing. Refer to https://github.com/AdoptOpenJDK/JCK8/issues/3 for more information
