### ISSUE TITLE
System testing hung at OpenJ9

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-systemtest#184]
Some system testing hung in the OpenJ9 nightly builds. Seems related to reading from cvs, the next step in the previous build was `cvs export: Updating mauve`

https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_ppc-64_cmprssptrs_le/65/console
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/48/console

Last step in these hung builds was 
```
02:18:07 get-source:
02:18:08      [exec] Could not read password for host: java.io.FileNotFoundException: /home/jenkins/.cvspass (No such file or directory)
```

Last build showed
```
04:23:20.016 get-source:
04:23:21.620      [exec] Could not read password for host: java.io.FileNotFoundException: /home/jenkins/.cvspass (No such file or directory)
04:23:22.422      [exec] cvs export: Updating mauve
04:23:22.523      [exec] U mauve/.classpath
04:23:22.623      [exec] U mauve/.cvsignore
04:23:22.624      [exec] U mauve/.project
04:23:22.624      [exec] U mauve/COPYING
```

**Comment by Mesbah-Alam** [comment]
That FileNotFoundException happens in passing builds as well: https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/72/consoleFull. 

The hang seems to be happening in the cvs update step in the Java CVS client that the system tests use to checkout Mauve source.

**Comment by Mesbah-Alam** [comment]
The hang seems to occur intermittently in the [get-source](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/000511c3f1ca89675367b2ca6c08ac0edef5a707/openjdk.test.mauve/build.xml#L345) target in mauve build.xml 

```
	<target name="get-source" depends="download-cvsclient, create-work-dir" unless="already_built">
                <exec dir="${work_dir}" executable="java">
                                <arg value="-Dcvs.root=:pserver:anoncvs@sourceware.org:/cvs/mauve"/>
                                <arg value="-jar"/>
                                <arg value="${prereqs_root}/cvsclient/org-netbeans-lib-cvsclient.jar"/>
                                <arg value="export"/>
                                <arg value="-r"/>
                                <arg value="HEAD"/>
                                <arg value="mauve"/>
                </exec>
	</target>
```

Seen again here: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/366/console

We are using the Java CVS client to download mauve source code. There seems to be intermittent IO issues in this cvs client communicating with the mauve code repository server sourceware.org:/cvs/mauve.

**Comment by Mesbah-Alam** [comment]
Closing this issue at the moment as https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/187 should have solved it. Please re-open if the Hang happens again.
