### ISSUE TITLE
Use Pre-staged Mauve source in system test builds 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#187]
We may not need to checkout Mauve source every time a system test build (including Systemtest grinder) runs. We can instead have a job that checks out mauve source, zips it up and stores it in Jenkins. We can run this job daily/weekly. And the system tests can simply grab the last successful zip file containing the mauve source and uses it in the build. 

**Benefit**
1) This will help us get around the [hang issue](https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/184) we see with the Java cvs client in system test builds. 
2) It will help reduce noice in system test console output. 

**Questions to consider**
1) How often does the Mauve source change? 
2) How big the zip file would be? 

**Note**: 
We could pre-stage all system test prereq jars - to make the get dependency stage for system test more robust (https://github.com/AdoptOpenJDK/openjdk-tests/issues/637).

**Comment by Mesbah-Alam** [comment]
@lumpfish  @llxia  @smlambert  - FYI.

**Comment by Mesbah-Alam** [comment]
One thing to note is, we wouldn't want to touch the story of building and running systemtests locally-- that story should still be using the existing flow of systemtests fetching and building mauve.jar in place. Only the build triggered by Jenkins should be using the pre-built mauve.jar.

**Comment by smlambert** [comment]
Agree, this is only to stabilize the automated Jenkins builds.  For manual runs, they should continue to work as is.

**Comment by llxia** [comment]
Once this is stabilized, it is better to get the script checked into git repo instead of coding directly in Jenkins job. It is easier to maintain in git repo as we may want to create the same job on other Jenkins servers (OpenJ9 and internal).

**Comment by Mesbah-Alam** [comment]
Yes, I think the same should be done for the [test.GetDependency ](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test.getDependency/)build as well.

**Comment by Mesbah-Alam** [comment]
Tested by r[unning system tests locally using TestConfig](https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md) that mauve source does get cloned and built as it should when run locally.

**Comment by Mesbah-Alam** [comment]
The systemtest.getDependency job in the internal jenkins ci system is running fine too. The related PRs to this issue have thus been delivered.
