### ISSUE TITLE
can't import jtb 

### ISSUE THREAD

**Issue by navyxliu** [AdoptOpenJDK/openjdk-systemtest#189]
I do think these 2 lines are correct. 
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/000511c3f1ca89675367b2ca6c08ac0edef5a707/openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java#L653

I got an error to execute jtlite.jar when I tried to import the jtb files which contains these 2 lines. 
I am running JCK8b on Linux. 

bash-4.2# /openjdkbinary/j2sdk-image/bin/java -jar /jck_root/jck8b/JCK-runtime-8b/lib/jtlite.jar  -config /jvmtest/systemtest/openjdk-systemtest/openjdk.test.jck/config/jck8b/runtime.jti @/test/TestConfig/test_output_1541636630654/20181108-002351-Jck/results/JTB/stf_generated.jtb
+ set jck.env.runtime.remoteAgent.passiveHost localhost
Configuration file can not be imported due to question with specified tag "jck.env.runtime.remoteAgent.passiveHost" was not found on path. The path is:jck.intro

**Comment by Mesbah-Alam** [comment]
The jck8 tests are running fine in the internal builds. Is it still a problem at your end @navyxliu?

**Comment by navyxliu** [comment]
yes.  it looks good. 
my fault. I guess I invoked it with  some wrong command arguments. I close it.
