### ISSUE TITLE
systemtest attempts to use pre-staged mauve.jar when compiled locally with TestConfig

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#193]
Running systemtests locally with TestConfig will fail trying to copy mauve.jar from getDependency build. 

Steps: 
```
1. git clone https://github.com/AdoptOpenJDK/openjdk-tests.git
2.  cd /openjdk-tests
3. ./get.sh -t ../openjdk-tests -p x64_linux -i openj9 (if you are using an openj9 or ibm jdk; use 'openjdk' otherwise) 
4. cd TestConfig
5. export SPEC=linux_x86-64_cmprssptrs
6.  export BUILD_LIST=systemtest
7. Export JAVA_HOME=<JAVA_HOME_DIR>
8. Export JAVA_BIN=<JAVA_BIN_DIR>
9. make -f run_configure.mk
10. make compile
```

The compile step will end up invoking [configure_systemtest](https://github.com/AdoptOpenJDK/openjdk-tests/blob/7f959e7be0ea44844918dc1e65949aef8939764a/systemtest/build.xml#L168) which will invoke openjdk.build/build.xml with "isAutomatedBuild" flag set to true -- which will in turn run `fetch-prestaged-mauve-jar` target, instead of `run-mauve-configure` target from openjdk.build/include/top.xml. 

We have to find out a way to distinguish between whether or not we are running systemtests manually/locally using TestConfig, or in a Jenkins build environment -- and only attempt to use a pre-staged mauve.jar for the latter case. 

Note: this is not a road blocker as we can still compile and run systemtests locally using the systemtest make story.

**Comment by llxia** [comment]
I did not look into the system test code for this. Just from the description, could we just download the jar if jar does not exist or sha does not match (regardless what kind build is it)? 

We do this for functional test jars https://github.com/eclipse/openj9/blob/master/test/TestConfig/scripts/tools/getDependencies.pl

**Comment by Mesbah-Alam** [comment]
Yes, I am making a PR with the change.
