### ISSUE TITLE
JlinkTest_RequiredMod fails on osx

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#203]
With error: 
```
STF 04:04:37.193 - Monitoring processes: T2 
T2  JUnit version 4.12
T2  stderr Exception in thread "main" java.lang.UnsatisfiedLinkError: JniTest (Not found in java.library.path)
T2  stderr 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1678)
T2  stderr 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1648)
T2  stderr 	at java.base/java.lang.System.loadLibrary(System.java:559)
T2  stderr 	at com.test.jlink/adoptopenjdk.test.modularity.jlink.JniTest.<clinit>(JniTest.java:24)
T2  stderr 	at java.base/java.lang.Class.forNameImpl(Native Method)
T2  stderr 	at java.base/java.lang.Class.forName(Class.java:409)
T2  stderr 	at org.junit.internal.Classes.getClass(Classes.java:16)
T2  stderr 	at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:100)
T2  stderr 	at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
T2  stderr 	at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
T2  stderr 	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
T2  stderr 	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
```

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-osx_x86-64_cmprssptrs/3/tapResults/

**Comment by Mesbah-Alam** [comment]
Note: the same test works fine on other platforms.

**Comment by lumpfish** [comment]
I've rerun this test on jdk11 and jdk15 and it passes:
jdk11
openj9: https://ci.adoptopenjdk.net/job/Grinder/4590/
hotspot: https://ci.adoptopenjdk.net/job/Grinder/4606/
jdk15
openj9: https://ci.adoptopenjdk.net/job/Grinder/4607/
hotspot: https://ci.adoptopenjdk.net/job/Grinder/4608/

I suggest the test be reinstated.  Should it reoccur we will be able to see whether the failure is intermittent or restricted to certain test machines.

**Comment by lumpfish** [comment]
Looks like this is because we build a .so file on osx rather than a .dylib.
PR to fix: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/374
PR to reenable the tests: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2048
Test runs:
jdk11:
openj9: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4616/
hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4617/
jdk15:
openj9: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4618/
hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4619/

**Comment by Mesbah-Alam** [comment]
Thanks fo finding this out @lumpfish . Just wondering, do we also need to add this flag in the other makefile we have in [openj9.test.sharedClasses.jvmti](https://github.com/eclipse/openj9-systemtest/blob/master/openj9.test.sharedClasses.jvmti/src/native/Makefile#L168)?

**Comment by lumpfish** [comment]
>  Just wondering, do we also need to add this flag in the other makefile we have in [openj9.test.sharedClasses.jvmti](https://github.com/eclipse/openj9-systemtest/blob/master/openj9.test.sharedClasses.jvmti/src/native/Makefile#L168)?

I would assume anywhere we create a jni native library.  I've just been going through the outstanding issues and exclusions one by one so I haven't dug around for more occurrences.

**Comment by smlambert** [comment]
Closed via https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/374
