### ISSUE TITLE
SystemTest fails to compile on Windows - Illegal Character

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-systemtest#204]
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/de7fdf5639f3fb6842a229a76c35a8195f828d6d/openjdk.test.modularity/src/common-override/java.xml/javax/xml/namespace/QName.java#L24

https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/98

```
build-java:
     [echo] Ant version is Apache Ant(TM) version 1.10.3 compiled on March 24 2018
    [apply] C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\openjdk-systemtest\openjdk.test.modularity\src\common-mods\displayServiceImpl1\module-info.java:15: warning: [module] module name component displayServiceImpl1 should avoid terminal digits
    [apply] module displayServiceImpl1 {
    [apply]        ^
    [apply] C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\openjdk-systemtest\openjdk.test.modularity\src\common-mods\displayServiceImpl2\module-info.java:15: warning: [module] module name component displayServiceImpl2 should avoid terminal digits
    [apply] module displayServiceImpl2 {
    [apply]        ^
    [apply] 2 warnings
    [apply] C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\openjdk-systemtest\openjdk.test.modularity\src\common-override\java.xml\javax\xml\namespace\QName.java:24: error: illegal character: '\u2039'
    [apply] 	public String getLocalPartâ€‹() {
    [apply] 	                            ^
    [apply] 1 error

BUILD FAILED
C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\TestConfig\scripts\build_test.xml:71: The following error occurred while executing this line:
C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\build.xml:200: The following error occurred while executing this line:
C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.build\build.xml:69: The following error occurred while executing this line:
C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.build\build.xml:49: The following error occurred while executing this line:
C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\openjdk-systemtest\openjdk.build\build.xml:66: The following error occurred while executing this line:
C:\Users\jenkins\workspace\Test-Grinder\openjdk-tests\systemtest\openjdk-systemtest\openjdk.test.modularity\build.xml:133: apply returned: 1
```

**Comment by Mesbah-Alam** [comment]
This was seen on AIX too https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-aix_ppc-64_cmprssptrs/85/console

The special character appeared on AIX in a file I have recently added, it's a plain and simple Java file that was created by hand. There were a few extra spaces that I [removed](https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/201/files) after seeing the error on AIX, and it subsequently went away in the next AIX build: https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-aix_ppc-64_cmprssptrs/86/console

I am not sure exactly why this special character appears in the Java file - it is now appearing on Windows too apparently. 

Any idea ?

**Comment by Mesbah-Alam** [comment]
This seems to be a machine issue, the system test builds normally on Windows in ci.adopt nightly builds : https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/95/consoleFull

Closing this issue. Please re-open it if it happens again.

**Comment by AdamBrousseau** [comment]
Still happening
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/109/console

**Comment by Mesbah-Alam** [comment]
Why doesn't it happen in the Build? It seems to be an intermittent machine issue.

**Comment by AdamBrousseau** [comment]
The only system test on Windows enabled at the moment is jdk8
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/
The rest haven't been turned on yet. Should I enable them all?

**Comment by Mesbah-Alam** [comment]
Systemtest builds on Windows at Openj9 are currently blocked by https://github.com/eclipse/openj9/issues/3897 . So, I suggest we do not enable other JDK versions yet.
