### ISSUE TITLE
replaceAll("lib", "bin") does't work on conventional rpm install paths

### ISSUE THREAD

**Issue by navyxliu** [AdoptOpenJDK/openjdk-systemtest#205]
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/de7fdf5639f3fb6842a229a76c35a8195f828d6d/openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java#L461

I'm using the JCK plugin to test a RPM of JDK8.  

Because our rpm installs `/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/`,  my `root` here is 
`/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre/lib`

The following code is buggy. It will substitute all "lib" with "bin".  As a result, NPE will throw when it iterates files in the folder `/usr/bin/jvm/java-1.8.0-amazon-corretto.x86_64/jre/bin`. 
```java
String newRoot = root.replaceAll("lib", "bin");
```

I think this is better.  In my understanding, newroot is the sibling folder "bin" of root. It only needs to substitute the last appearance of "lib". 
 
```java
String newRoot = new File(root).getParent() + File.separator + "bin";
```

**Comment by smlambert** [comment]
I believe you are correct @navyxliu that the intent in src/test.jck/net/adoptopenjdk/stf/Jck.java#L461 is for the last lib to be replaced.  I can create a PR shortly.

**Comment by Mesbah-Alam** [comment]
@navyxliu - can this issue be closed now?

**Comment by smlambert** [comment]
I believe this has been addressed, please re-open if not the case.
