### ISSUE TITLE
TestJlmRemoteThreadNoAuth_SE80_0 fails on Windows intermittently 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#208]
Passes here: https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/106/tapResults/

But fails here: https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/107/tapResults/

When it fails, it fails due to the CL2 process ending with non-zero result code.

**Comment by Mesbah-Alam** [comment]
5x Grinder link: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/646/console

**Comment by Mesbah-Alam** [comment]
May be dup : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/145

**Comment by Mesbah-Alam** [comment]
Test excluded from Windows: https://github.com/AdoptOpenJDK/openjdk-tests/pull/751

**Comment by lumpfish** [comment]
I've seen this on other platforms too.  Maybe the tests is simply taking longer to run on some test machines that others and timing out?
