### ISSUE TITLE
SharedClassesAPI_0 extended "libsharedClasses.so could not be opened" on linux, aix, osx

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-systemtest#212]
SharedClassesAPI_0 started failing in the extended system test run at the OpenJ9 project.
```
JVMT stderr JVMJ9TI001E Agent library /home/jenkins/workspace/Test-extended.system-JDK11-linux_x86-64/jvmtest/systemtest/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux_x86-64/libsharedClasses.so could not be opened (/home/jenkins/workspace/Test-extended.system-JDK11-linux_x86-64/jvmtest/systemtest/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux_x86-64/libsharedClasses.so: cannot open shared object file: No such file or directory)
JVMT stderr JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed
STF 06:13:34.118 - **FAILED** Process JVMT ended with exit code (1) and not the expected exit code/s (0)
```

https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_390-64_cmprssptrs/133
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_390-64_cmprssptrs/109

https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_x86-64/129
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64/112
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_x86-64_cmprssptrs/128
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/116

https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_ppc-64_cmprssptrs_le/127
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_ppc-64_cmprssptrs_le/111

https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-osx_x86-64_cmprssptrs/6
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-osx_x86-64_cmprssptrs/22

https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-aix_ppc-64_cmprssptrs/122

**Comment by pshipton** [comment]
@Mesbah-Alam @smlambert

**Comment by Mesbah-Alam** [comment]
@pshipton - this failure was introduced by a change made by me in the sharedClasses.jvmti compile makefile recently. This will resolve it: https://github.com/eclipse/openj9-systemtest/pull/59

**Comment by pshipton** [comment]
Guess I opened this at the wrong place? I'll just close it since we have a fix in hand.
