### ISSUE TITLE
stf.pl fails with path name too long on Windows 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#215]
```
Running test SharedClassesWorkloadTest_Softmx_Increase_JitAot_0 ...
===============================================
SharedClassesWorkloadTest_Softmx_Increase_JitAot_0 Start Time: Wed Jan  2 04:03:25 2019 Epoch Time (ms): 1546423405962
variation: NoOptions
JVM_OPTIONS:  -Xcompressedrefs 
Uncaught exception from user code:
	mkdir C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/\TestConfig\test_output_15464227613621\SharedClassesWorkloadTest_Softmx_Increase_JitAot_0/20190102-040326-SharedClassesWorkloadTest_Softmx_Increase_JitAot/debug: No such file or directory; The filename or extension is too long at C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests///..//jvmtest\systemtest\stf\stf.core\scripts\stf.pl line 324.
	File::Path::_mkpath(HASH(0x9b82c0), ARRAY(0x9b83f8)) called at C:/Strawberry/perl/lib/File/Path.pm line 154
	File::Path::mkpath("C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-"...) called at C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests///..//jvmtest\systemtest\stf\stf.core\scripts\stf.pl line 324
STF 04:03:26.681 - =========================   S T F   =========================
systemtest-prereqs has been processed, and set to: C:/Users/jenkins/workspace/Test-extended.system-JDK8-win_x86-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs
SharedClassesWorkloadTest_Softmx_Increase_JitAot_0_FAILED
```

https://ci.eclipse.org/openj9/view/Test/job/Test-extended.system-JDK8-win_x86-64_cmprssptrs/123/tapResults/

**Comment by Mesbah-Alam** [comment]
The name of the failing tests are indeed unnecessarily long in the playlist. The simple solution of this error would be to update the test names into reasonable and shortened alternatives.

**Comment by Mesbah-Alam** [comment]
Note: the problem was not reproducible at Adopt:  https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/713/console

**Comment by llxia** [comment]
In openj9, the path is longer with job name `Test-extended.system-JDK8-win_x86-64_cmprssptrs`, whereas a shorter job name `Grinder` is used above at Adopt. We are comparing a different path length here. A further investigation may be needed.

**Comment by Mesbah-Alam** [comment]
The new names should work in the regular builds as well, since the new names have been made shorter than `SharedClassesWorkloadTest_Softmx_Increase` - which worked successfully on the same machine where the others failed: https://ci.eclipse.org/openj9/view/Test/job/Test-extended.system-JDK11-win_x86-64_cmprssptrs/120/tapResults/

**Comment by Mesbah-Alam** [comment]
The problem is resolved: https://ci.eclipse.org/openj9/view/Test/job/Test-extended.system-JDK8-win_x86-64_cmprssptrs/128/tapResults/
