### ISSUE TITLE
Test aarch64 developer builds with System tests

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#229]
Run some system test Grinders on the aarch64 developer builds made by Kazuhiro Konno/Japan/IBM.  

Note: His builds are 'interpreter only', so will run slow, so suggest 1 target at a time, not entire sanity set together. 

We need to update the openj9-systemtest repo to compile systemtest natives for that platform (https://github.com/eclipse/openj9-systemtest/issues/84).

Builds are here: 

1) LargeHeap one, https://ci.adoptopenjdk.net/view/Test_grinder/job/UploadFile/9/artifact/upload/jdk20190213.zip.
2) CR one:  https://ci.adoptopenjdk.net/view/Test_grinder/job/UploadFile/10/artifact/upload/jdk20190308cr.zip

We only have aarch64 machines at Adopt, so that is where the Grinders must get run for now.

**Comment by Mesbah-Alam** [comment]
Here's a Grinder build that runs a system test successfully using Hiro's large heap sdk: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1187/console

**Comment by Mesbah-Alam** [comment]
ClassLoadingTest_0 fails with Hiro's CR build with failure: 

```
CLT stderr JVMDUMP039I Processing dump event "user", detail "" at 2019/03/11 17:04:32 - please wait.
CLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170432.4545.0001.txt' in response to an event
CLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170432.4545.0001.txt
CLT stderr JVMDUMP013I Processed dump event "user", detail "".
CLT stderr JVMDUMP039I Processing dump event "user", detail "" at 2019/03/11 17:05:02 - please wait.
CLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170502.4545.0002.txt' in response to an event
CLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170502.4545.0002.txt
CLT stderr JVMDUMP013I Processed dump event "user", detail "".
CLT stderr JVMDUMP039I Processing dump event "user", detail "" at 2019/03/11 17:05:32 - please wait.
CLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170532.4545.0003.txt' in response to an event
CLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170532.4545.0003.txt
CLT stderr JVMDUMP013I Processed dump event "user", detail "".
CLT stderr JVMDUMP039I Processing dump event "abort", detail "" at 2019/03/11 17:06:02 - please wait.
CLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/core.20190311.170602.4545.0004.dmp' in response to an event
CLT stderr JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.8116.
CLT stderr 
CLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/core.20190311.170602.4545.0004.dmp
CLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170602.4545.0005.txt' in response to an event
CLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/javacore.20190311.170602.4545.0005.txt
CLT stderr JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/Snap.20190311.170602.4545.0006.trc' in response to an event
CLT stderr JVMDUMP010I Snap dump written to /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_1552322058603/ClassLoadingTest_0/20190311-163419-ClassloadingLoadTest/results/Snap.20190311.170602.4545.0006.trc
CLT stderr JVMDUMP013I Processed dump event "abort", detail "".
```
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1202/tapResults/

**Comment by Mesbah-Alam** [comment]
Hi @smlambert , I've been running 1 target at a time using Hiro's builds. But the process is extremely slow. For example, the following build to **2h45m** to complete: 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1202/ 

The slowness is apparently in the compilation process, which takes longer than usual. 

I am wondering if we could run a batch of tests together in one build; as opposed to 1 target per build.

**Comment by smlambert** [comment]
yes, we have had additional aarch64 machines added at Adopt project yesterday, so feel free to run all of sanity and extended targets in one run now.  As it won't block other testing, since we now have [13 machines](https://ci.adoptopenjdk.net/label/hw.arch.aarch64/) instead of 1.

**Comment by Mesbah-Alam** [comment]
Failure summary of `sanity.system` [test run](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1210/tapResults/) against Hiro's aarch64 CR build: 
- Concurrent scavenge tests are failing - I suspect concurrent scavenge feature has not been enabled in this SDK yet. 
- There are two real failures: 
1) Class loading load test failed both with CR and non-CR sdk (with same crash as mentioned in https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/229#issuecomment-471648127). Running a [5x Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1216/console) just with this test- will open a PR for it with grinder results.
2) CpMpJlinkTest_0 test fails with the "jlink" command timing out. Running a [5x Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1217/console) with this test to find out consistency of this failure. Will open PR after.

**Comment by Mesbah-Alam** [comment]
Jlink timeout failure is intermittent , happened 1/5 times in the Grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1219/tapResults/

**Comment by Mesbah-Alam** [comment]
ClassLoading load test failed 5/5 times in grinder, opened a new openj9 issue for this failure: https://github.com/eclipse/openj9/issues/5071

**Comment by Mesbah-Alam** [comment]
Grinder running `sanity.system` with increased timneout: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/24/console
