### ISSUE TITLE
Mauve load test fails on JDK11 and JDK12  

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#234]
MauveSingleInvocationLoadTest and MauveSingleThreadLoadTest Fail on all platforms with following error: 

```
LT  FAIL: gnu.testlet.javax.swing.DefaultListSelectionModel.setSelectionInterval: SINGLE_SELECTION_X (number 7)
LT  got 2 but expected 4
```

**On Adopt:** 

The single invocation and single thread load test fail across platform - and needs to be disabled
However, Mauve Multithread load test is working

https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_ppc64le_linux/187/tapResults/

**On OpenJ9** 

**JDK11** 

https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK11-linux_x86-64/207/tapResults/

JDK12: 

MauveSingleThreadLoadTest_OpenJ9_0 test fails with the same error above:
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK12-linux_390-64_cmprssptrs/29/tapResults/

**Comment by Mesbah-Alam** [comment]
Tests excluded https://github.com/AdoptOpenJDK/openjdk-tests/pull/1019

**Comment by smlambert** [comment]
Also seen against hotspot:
https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_macos/15/tapResults/
https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_windows/14/tapResults/

**Comment by Mesbah-Alam** [comment]
The hotspot version of the failing tests have been disabled too:  
`MauveSingleInvocationLoadTest_HS` 
`MauveSingleThreadLoadTest_HS`

**Comment by Mesbah-Alam** [comment]
Closing via https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/237
