### ISSUE TITLE
HCRLateAttachWorkload test times out on Windows on JDK8 OpenJ9 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#236]
HCRLateAttachWorkload test times out on Windows on JDK8 OpenJ9 

```
LT  02:32:23.429 - Test stopped due to reaching runtime limit
LT  02:32:23.429 - Load test completed
LT  02:32:23.429 -   Ran     : 5333
LT  02:32:23.429 -   Passed  : 5333
LT  02:32:23.429 -   Failed  : 0
LT  02:32:23.429 -   Result  : PASSED
STF 02:37:20.165 - Heartbeat: Process AG  is still running
STF 02:37:22.227 - **FAILED** Process AG  has timed out
```
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-win_x86-64_cmprssptrs/205/tapResults/

**Comment by Mesbah-Alam** [comment]
Running 5x Grinder after increasing the timeout of the failing process : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/71/console

**Comment by Mesbah-Alam** [comment]
The program actually "hangs" infinitely inside the while loop in Attacher.java waiting for the VM to connect to, as evident in here: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/78/console

The PID `StfConstants.PERL_PROCESS_PID =1` , however the VirtualMachine.list() returns two VMs with PIDs 11848 & 8412, so there is no matching VM found with passed in PID (=1). Hence the program keeps sleeping and retrying. 

Running the same test on Linux to see why it passes on that platform: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/79/console

**Comment by Mesbah-Alam** [comment]
On Linux, the test finds a VM to attach to whose PID matches that of the passed on PID: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/80/console

Wndows: 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/81/console

**Comment by Mesbah-Alam** [comment]
The vmPidArg value that the Attacher receives from the test comes from 

```
JavaProcessDefinition testProcess2 = test.createJavaProcessDefinition() 
				.addJarToClasspath(agentJar)
				.addJarToClasspath(toolsJar)
				.runClass("net.adoptopenjdk.test.hcrAgent.agent.Attacher")
				.addPerlProcessData(miniMixProcess,StfConstants.PERL_PROCESS_PID)
				.addArg(agentJar.toString())
				.addArg(agentOptions);
```

Where

`.addPerlProcessData(miniMixProcess,StfConstants.PERL_PROCESS_PID)` - return 6890 on Linux, and 260 on Windows.

**Comment by Mesbah-Alam** [comment]
@lumpfish - do you know if this test ever worked on Windows? 

JavaProcessDefinition#addPerlProcessData() doesn't seem to be doing what it's supposed to do on Windows (it works on non-Windows platforms).

**Comment by lumpfish** [comment]
This is fixed by https://github.com/AdoptOpenJDK/stf/pull/89

Created PR to reinstate the tests: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2046
