### ISSUE TITLE
How to tell which systemtest sha's are used for testing

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-systemtest#245]
How do I tell which systemtest sha's are being used when running system tests? I'd like to be able to tell if the system test material changed between runs, and use git to look at a comparison to see what changed.

Looking at an example run, I see the following, but it doesn't show any sha's.
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/302
```
01:30:14  clone_stf:
01:30:14       [echo] Cloning from: https://github.com/AdoptOpenJDK/stf.git -b master
01:30:14       [exec] Cloning into 'stf'...
01:30:15       [echo] /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/../systemtest/openjdk-systemtest does not exist, clone from GitHub
01:30:15  
01:30:15  clone_systemtest:
01:30:15       [echo] Cloning from: https://github.com/AdoptOpenJDK/openjdk-systemtest.git -b master
01:30:15       [exec] Cloning into 'openjdk-systemtest'...
01:30:16       [echo] /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/../systemtest/openj9-systemtest does not exist, clone from GitHub
01:30:16  
01:30:16  clone_openj9-systemtest:
01:30:16       [echo] Cloning from: https://github.com/eclipse/openj9-systemtest.git -b master
01:30:16       [exec] Cloning into 'openj9-systemtest'...
``

**Comment by pshipton** [comment]
@smlambert @Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
The git checkout of systemtest materials (e.g. https://github.com/AdoptOpenJDK/openjdk-tests/blob/0b48afa31bdca7b1f0a34163c4cd31a4dacea882/systemtest/common.xml#L51) are checking code out from master by default (in all regular test builds everywhere) and if any developer fork/branch is specified (e.g. from Grinder-systemtest), it's checking out from there. 

Are you looking to see SHA information of the last committed change(s) that went into master of the 3 related system test repos in job output?

**Comment by pshipton** [comment]
> Are you looking to see SHA information of the last committed change(s) that went into master of the 3 related system test repos in job output?

Yes. The contents of master, or any fork/branch, can change from build to build. I'd like the SHAs which are checked out to be printed so its obvious which level of the system tests are running. I should be able to look at these SHAs from different builds to determine if the system test material changed. If it did change, anyone can construct a simple git/github query to show the differences.

**Comment by smlambert** [comment]
We also need to gather this info as part of the [AdoptOpenJDK Quality Assurance (AQA)](https://github.com/AdoptOpenJDK/openjdk-tests/issues/965) story.

FYI @llxia has already been looking at some of this (gathering metadata to be able to fully reproduce a test run, with the exact same test material).

**Comment by Mesbah-Alam** [comment]
@pshipton , is the following out enough (will repeat this for all 3 repos, and for whichever repo+branch is being cloned in the build of course):

```
git ls-remote https://github.com/AdoptOpenJDK/openjdk-systemtest master
f32d7e662799a5a28271da0a054c0148d7d22c03	refs/heads/master
```

**Comment by pshipton** [comment]
@Mesbah-Alam yes, this is fine.
