### ISSUE TITLE
Mauve incompatible with Java 13

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-systemtest#260]
I ran the system tests on an OpenJ9 Java 13 build, and found the following failure. It's likely related to changes in Java 13, and not specific to OpenJ9.

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_x86-64_windows_OpenJDK/1
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_ppc64le_linux_OpenJDK/1
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_x86-64_linux_xl_OpenJDK/1
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_s390x_linux_OpenJDK/1
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_x86-64_linux_OpenJDK/1
```
LT  12:18:22.536 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
LT  12:18:22.537 - suite.getInventory().getInventoryFileRef(): openjdk.test.load/config/inventories/mauve/mauve_all.xml
LT  12:18:22.537 - suite.isCreateDump() : false
LT  12:18:22.538 - Test failed
LT    Failure num.  = 1
LT    Test number   = 4003
LT    Test details  = 'Mauve[gnu.testlet.java.util.logging.Handler.isLoggable]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  FAIL: gnu.testlet.java.util.logging.Handler.isLoggable (number 0)
LT  <<<
```

**Comment by Mesbah-Alam** [comment]
So, the following test needs to be disabled 

```
 FAIL: gnu.testlet.java.util.logging.Handler.isLoggable
```

**Comment by pshipton** [comment]
I built a Hotspot Java 13 and confirmed the same failure occurs.
```
19:16:05  openjdk version "13-internal" 2019-09-17
19:16:05  OpenJDK Runtime Environment (build 13-internal+0-adhoc.pete.jdk)
19:16:05  OpenJDK 64-Bit Server VM (build 13-internal+0-adhoc.pete.jdk, mixed mode, sharing)

built from "tip"
tip                            54929:657f6e484bc6
jdk-13+21                      54890:f2f11d7f7f4e
```
```
LT  17:05:03.001 - Starting thread. Suite=0 thread=0
LT  17:05:05.933 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
LT  17:05:05.935 - suite.getInventory().getInventoryFileRef(): openjdk.test.load/config/inventories/mauve/mauve_all.xml
LT  17:05:05.935 - suite.isCreateDump() : false
LT  17:05:05.958 - Test failed
LT    Failure num.  = 1
LT    Test number   = 4003
LT    Test details  = 'Mauve[gnu.testlet.java.util.logging.Handler.isLoggable]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  FAIL: gnu.testlet.java.util.logging.Handler.isLoggable (number 0)
LT  <<<
```

**Comment by pshipton** [comment]
I note the following in the Java 13 release notes http://jdk.java.net/13/release-notes

NullPointerException in java.util.logging.Handler#isLoggable (JDK-8216363)
core-libs/java.util.logging

The default implementation of java.util.logging.Handler.isLoggable is updated to match its specification, and to return false if the record parameter is null. The implementation of java.util.logging.MemoryHandler.isLoggable and java.util.logging.MemoryHandler.publish will no longer throw NullPointerException if the record parameter is null which conforms to their specification.

**Comment by Mesbah-Alam** [comment]
Should we exclude this test from running then, in order to allow mauve to work on Java 13?

**Comment by pshipton** [comment]
I believe so, at least for Java 13.
