### ISSUE TITLE
sanity.system assertion failure on x86-64_linux_xl

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-systemtest#270]
TestIBMJlmRemoteMemoryAuth_0 and TestIBMJlmRemoteMemoryNoAuth_0 seem to fail when LT1 completes its workload before CL1 has finished performing monitoring actions on LT1.

I don't have a failure at OpenJ9 jenkins ci job, but this is seen when running on a CENT6 docker container.  Same job as this one.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_xl_Nightly/

```
01:06:01.899  STF 02:41:16.030 - +------ Step 5 - Wait for the processes to complete
01:06:01.899  STF 02:41:16.030 - | Wait for processes to meet expectations
01:06:01.899  STF 02:41:16.030 - |   Processes: [LT1, CL1]
01:06:01.899  STF 02:41:16.030 - |
01:06:01.899  STF 02:41:16.031 - Monitoring processes: CL1 LT1
01:06:02.868  CL1 j> 2019/06/03 02:41:17.013 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
01:06:09.688  CL1 j> 2019/06/03 02:41:22.780 Monitored VM not ready at Jun 3, 2019, 2:41:22 AM (attempt 0).
01:06:09.688  CL1 j> 2019/06/03 02:41:22.781 Wait 5 secs and trying again...
01:06:15.055  CL1 j> 2019/06/03 02:41:28.702 Connection established!
01:06:16.472  CL1 j> 2019/06/03 02:41:30.407 Starting to write data
01:10:29.855  STF 02:45:38.453 - **FAILED** Process LT1 has ended unexpectedly
01:10:29.855  CL1 .......................j> 2019/06/03 02:45:38.320 Exiting as JVM we are connected to has finished
01:10:29.855  CL1 stderr Exception in thread "main" java.lang.AssertionError
01:10:29.855  CL1 stderr 	at org.junit.Assert.fail(Assert.java:86)
01:10:29.855  CL1 stderr 	at org.junit.Assert.fail(Assert.java:95)
01:10:29.855  CL1 stderr 	at net.openj9.test.jlm.remote.MemoryProfiler.getStatsViaProxy(MemoryProfiler.java:217)
01:10:29.855  CL1 stderr 	at net.openj9.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:119)
01:10:29.855  STF 02:45:38.454 - Monitoring Report Summary:
01:10:29.855  STF 02:45:38.454 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
01:10:29.855  STF 02:45:38.454 -   o Process LT1 has ended unexpectedly
01:10:29.855  STF 02:45:38.455 - Killing processes: CL1 LT1
01:10:29.855  STF 02:45:38.455 -   o Process LT1 is not running
01:10:29.855  STF 02:45:38.455 -   o Process CL1 is not running
```

fyi @Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
The client is complaining that the server process has finished, while the client is still attempting to make JLM API calls to the server. 

Discussing with Joe revealed that - on this particular occasions there more than normal number of CPU's being used in the server process - which might be the reason for the server to finish faster than usual. 

We had previously increased workload on the server process to make it run faster - but that had its own side effect - of taking up too much memory. 

Regardless, I feel the test strategy used in the JLM system tests should be revisited in general - we likely don't want the client to to fail the test if the server stops. The test should be more robust.

**Comment by lumpfish** [comment]
This is fixed by https://github.com/eclipse/openj9-systemtest/pull/118.
