### ISSUE TITLE
wget failed to find libeay32.dll 

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-systemtest#29]
Build.md needs to be updated with the solution to fix the issue with wget dependencies

https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/docs/build.md

**Comment by chandrams** [comment]
@BhargaviMullapudi - As discussed please work on this issue

**Comment by karianna** [comment]
I don't see @BhargaviMullapudi as a member on GitHub?  If s/he can join then I'll add them to the team :-)

**Comment by lumpfish** [comment]
Fixed in https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/39
