### ISSUE TITLE
Upadate load tests to dynamically choose reduced loads for special slow running modes

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#292]
We should update the system test load tests to dynamically detect if special slow running jvm options are being used (e.g. -Xjit:count=0) and use a reduced load if true. 

Background: 

From https://github.com/eclipse/openj9-systemtest/issues/95#issuecomment-529676932

> FYI a system test run on JDK11, which resulted in a number of timeout problems.
> https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Special-System-JDK11/2/
> 
> ppcle
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal/39/
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal/40 - Daa Timeout has been exceeded
> 
> xLinux
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_Personal/1/
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_Personal/2 - timeout while running DaaLoadTest_all_special_19 Mode 550
> 
> xLinux XL
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/1/
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/5/ - MathLoadTest_bigdecimal_special_9
> 13:12:17 variation: Mode113
> 13:12:17 JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:gencon -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xmn512k -Xnocompressedrefs
> FAILED Process MLT has timed out
> 
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/2/ - timeout while running DaaLoadTest_daa2_special_5 Mode109

**Comment by Mesbah-Alam** [comment]
Analyzing results of the special nightly test builds in jdk11 with Pete yields that it's the MathLoadTest variations and DAA load test variations that we need to update to use lower workload when it comes to special nodes. They rest seem to finish relatively quickly. We should deliver the change for MathLoadTest and DAA load test and observe the overall performance of the special test and take it from there.

**Comment by pshipton** [comment]
Thanks Mesbah. Things are looking better now and I've stopped looking for slowness issues. We can close this now.

**Comment by Mesbah-Alam** [comment]
Closing this work item at the moment, as we have re-tuned all the system tests that needed re-tuning for special modes so far. We can re-open it if we need any to update any more tests in future.
