### ISSUE TITLE
Create a warm-up mechanism for load test to assess machine capability 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#294]
We should create a warm-up mechanism for STF load tests to assess machine capability based on which we can dynamically assign workloads so that load tests can end in a specific amount of time across all machines. 

Machine capabilities vary in different machines because of which a specific load test may take  different lengths of time on different machines to complete-- resulting in occasional timeouts on slow running old machines.  

A "warmup" capability can run a small amount of load and determine capability of the current machine. Based on this we can adjust the amount of workload we would want to run. 

This will free us up from having to manually adjust workloads.

**Comment by smlambert** [comment]
Can you leverage or extend MachineInfo test target?

**Comment by lumpfish** [comment]
The downside to this approach is that the tests become inconsistent across different platforms or consecutive runs across the same platform - so if for instance the test fails on one platform but not another it may not be due to a jdk code difference between the platforms but due to what are effectively different tests (due to the different loading) being run on the different platforms.

The original design of the tests was to eliminate such variation so that such comparisons would be reasonably reliable.

**Comment by smlambert** [comment]
FYI @pshipton

**Comment by pshipton** [comment]
I don't think all of the special.system tests (modes) are running long enough to properly warm up the JIT. I feel this may contribute to the problem of not finding intermittent JIT problems, when the  problems can be found by other similar (internal) tests which run for a longer time. At the same time, other tests (modes) are taking too long, which isn't a problem for finding problems, but may cause the special.system tests to take excessive run time, which is problematic when available machine resources are limited. If the time to run tests is configurable, the user/tester can decide how long each mode should run based on available machine resources.

@fjeremic fyi

**Comment by Mesbah-Alam** [comment]
@pshipton - Do we still need this warm-up mechanism? 

The 'time-based load testing' strategy that we have recently decided to roll out makes creation of this 'warm-up' mechanism rather irrelevant.

**Comment by pshipton** [comment]
>  Do we still need this warm-up mechanism?

No.

> The 'time-based load testing' strategy that we have recently decided to roll out makes creation of this 'warm-up' mechanism rather irrelevant.

Agreed.
