### ISSUE TITLE
Grinders in parallel mode doesn't inherit all the parameters from the master job

### ISSUE THREAD

**Issue by cathyzhyi** [AdoptOpenJDK/openjdk-systemtest#315]
In my case, I specified a personal system test repo in the master job launching the grinders
![image](https://user-images.githubusercontent.com/14285834/70551003-aea50d80-1b44-11ea-9611-012fba903dc5.png)
and checked the `IS_PARALLEL` box
![image](https://user-images.githubusercontent.com/14285834/70551243-23784780-1b45-11ea-89f9-9b44c4ebd0ec.png)

but the grinders launched didn't pick up the specified system test repo.

**Comment by smlambert** [comment]
With the change in how we do parallel (no longer IS_PARALLEL=true, the new param called PARALLEL=Iterations), this should no longer be an issue.  We should confirm it then close this issue.

**Comment by llxia** [comment]
This issue is a dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1322 and it is fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1755

Verified in Ginder, so close this issue.
