### ISSUE TITLE
STF_COMMAND should be able to append extra STF perl options

### ISSUE THREAD

**Issue by TianyuZuo** [AdoptOpenJDK/openjdk-systemtest#32]
the `STF_COMMAND` defined in the x.build/makefile should be able to append extra STF perl options.

For example, the `-results-root` can only be added when tests are executed from perl script. If a user want to define extra results-root dir, he have to use perl script to run the test. With the ability of appending extra perl script options, we can add extra options to test execution. 

A proposal is changing 
`STF_COMMAND:=perl $(STF_ROOT)$(D)stf.core$(D)scripts$(D)stf.pl $(JAVA_ARGS_ARG) -test-root="$(STF_ROOT);$(OPENJDK_SYSTEMTEST_TARGET_ROOT)" -systemtest-prereqs="$(RESOLVED_PREREQS_ROOT)" ` 

to   

`STF_COMMAND:=perl $(STF_ROOT)$(D)stf.core$(D)scripts$(D)stf.pl $(JAVA_ARGS_ARG) -test-root="$(STF_ROOT);$(OPENJDK_SYSTEMTEST_TARGET_ROOT)" -systemtest-prereqs="$(RESOLVED_PREREQS_ROOT)" $(EXTRA_STF_OPTION)`

**Comment by TianyuZuo** [comment]
Hi @Mesbah-Alam  and @lumpfish  any opinion about this?

**Comment by lumpfish** [comment]
I prefer the approach of exposing stf command line arguments explicity rather than with a general STF_OPTIONS=xxx macro.
For results-root, we already have this issue: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/17
Is there another argument you need to set also?

**Comment by TianyuZuo** [comment]
Thanks for pointing me to the existing issue. The `results-root` is what we currently need.

**Comment by lumpfish** [comment]
The other issue with just allowing extra command line options to be added in the this way is that it is difficult to pass the options from the make command line to the actual command within the make target when the options contains quotes and whitespace.

**Comment by TianyuZuo** [comment]
Agree with Simon that whitespaces and quotes may be an issue if we want to add multiple extra command line options. Since most common options are available from make command line options, I will close this issue. If new options are needed, will open new issues to track them.
