### ISSUE TITLE
duplicate comma in Jck.java

### ISSUE THREAD

**Issue by TianyuZuo** [AdoptOpenJDK/openjdk-systemtest#33]
in https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java#L822, there is a duplicate comma, also in line 819.  Is this duplicate comma meaningful for something in the STF JCK test framework?

**Comment by lumpfish** [comment]
The string ends up as --add-modules="module1,module2,..." on the java command line for the JCK test.  The extra comma is not significant, just a typo.
