### ISSUE TITLE
Update system test to use log4j 2.13.3

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#347]
Update system test to use latest version of log4j which is 2.13.3. https://archive.apache.org/dist/logging/log4j/2.13.3/ 

There contains a fix needed by https://github.com/eclipse/openj9/issues/4005

```
Prevent LoggerContext from being garbage collected while being created. Fixes LOG4J2-2756.
https://logging.apache.org/log4j/2.x/changes-report.html#a2.13.1
```

Note: We should also update all reference to log4j in systemtest and stf documentations.

**Comment by smlambert** [comment]
@Mesbah-Alam - Do we have to run the system.getDependency jobs at the various servers following this update?

**Comment by Mesbah-Alam** [comment]
@smlambert - yes, thanks for reminding. I'll trigger them off.

**Comment by Mesbah-Alam** [comment]
systemtest.getDependency jobs have been run @ adopt, runtimes and svt Jenkins. New version of log4j is up for grabs for the next systemtest builds.
