### ISSUE TITLE
Ability for systemtest to self-tune based on machine info

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-systemtest#350]
For stress tests in this repo, there are often settings for default number of iterations and threads to use for each stress test that is manually configurable.  

It would be a nice enhancement to have the ability to augment the MachineInfo test, and use this information for the test to adjust based on what the machine is capable of performing (more iterations or threads or resources depending on machine).

**Comment by Mesbah-Alam** [comment]
Related issue: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/294

**Comment by smlambert** [comment]
I will close this issue as dup of #294.
