### ISSUE TITLE
JCK read me update

### ISSUE THREAD

**Issue by suman-mitra** [AdoptOpenJDK/openjdk-systemtest#36]
Under the section ""Executing the JCK tests via 'stf.pl'" we have listed "executiontype" and "withagent". We suggest removing them and just mention below 

executiontype: The stf automation runs tests in multijvm way.

**Comment by chandrams** [comment]
Addressed by https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/38, hence closing
