### ISSUE TITLE
MathApiTest.java results are unreliable

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-systemtest#376]
In openjdk-systemtest there is a test program MathApiTest.java, the intent of which is to ensure that math operations are consistent across implementations, platforms and releases.

The file was originally generated by executing the math operations against an openjdk reference implmentation (jdk7 x86-64_linux), and using the results as the expected result for the operation when reexecuted.

Over time it has become apparent that the test case is not safe, in that for double and float operations for the Math class there is allowable flexibility in the precision of the result as described in the API documentation  - e.g. https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html.  In the times when this situation has been encountered in the past the approach has been to modify MathApiTest.java file to accept the imprecise value as an acceptable result for that operation - e.g. see https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/80, https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/77

However, this means that:
1. The MathApiTest.java file can no longer be reproduced by the program which generated it (as it has since been modified manually)
2. There is no guarantee that more tests will not need modifying in the future
3. The test case is unreliable in the sense that when it fails one cannot be confident that the failure represents a real issue in the jdk under test

Unlike the Math class, the StrictMath class does not allow for loss of precision, and results should be consistent across implementations, platforms and releases.

This issue proposes that the test case be modified to be more robust and reliable, by using StrictMath operations to generate the expected test results and then using the StrictMath.ulp() method to establish the precision tolerance.

Once these factors are known it would be possible to call each operation using StrictMath, when the results should be identical to the reference implementation result, and Math, when the result can be checked that it lies within the range (StrictMath-result plus or minus the ulp value).

An example current test failure issue demonstrating this is https://github.com/AdoptOpenJDK/openjdk-tests/issues/1893

Here is some output from doing some investigation:

openj9 jvm (result is the same for both Math and StrictMath):
```
Math.exp(-1.2232D) = 0.29428694035725067
Math.ulp(-1.2232D) = 2.220446049250313E-16
Math.exp(-1.2232D) + Math.ulp(-1.2232D) = 0.2942869403572509
Math.exp(-1.2232D) - Math.ulp(-1.2232D) = 0.29428694035725045
StrictMath.exp(-1.2232D) = 0.29428694035725067
StrictMath.ulp(-1.2232D) = 2.220446049250313E-16
StrictMath.exp(-1.2232D) + StrictMath.ulp(-1.2232D) = 0.2942869403572509
StrictMath.exp(-1.2232D) - StrictMath.ulp(-1.2232D) = 0.29428694035725045
```

hotspot jvm (result is different for Math and StrictMath):
```
Math.exp(-1.2232D) = 0.2942869403572507
Math.ulp(-1.2232D) = 2.220446049250313E-16
Math.exp(-1.2232D) + Math.ulp(-1.2232D) = 0.29428694035725095
Math.exp(-1.2232D) - Math.ulp(-1.2232D) = 0.2942869403572505
StrictMath.exp(-1.2232D) = 0.29428694035725067
StrictMath.ulp(-1.2232D) = 2.220446049250313E-16
StrictMath.exp(-1.2232D) + StrictMath.ulp(-1.2232D) = 0.2942869403572509
StrictMath.exp(-1.2232D) - StrictMath.ulp(-1.2232D) = 0.29428694035725045
```

So if the change proposed here were made, then the test would check that
1. StrictMath.exp(-1.2232D) returns 0.29428694035725067
2. Math.exp(-1.2232D) returns a value >= 0.29428694035725045 and <= 0.2942869403572509 (the range determined by executing StrictMath.ulp(-1.2232D))

**Comment by smlambert** [comment]
This sounds like a very good strategy for improving the test material @lumpfish 👍

**Comment by lumpfish** [comment]
PR which implements the changes proposed above: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/378

There are two special cases included in the PR.
1. The precision of toRadians() was changed in openjdk between jdk8 and jdk9.  The test case now tolerates a 2 ulp difference for toRadians() results if the source code for the test cases was generated using jdk8 or earlier and the runtime jdk is later than jdk8 or vice versa, but not if the source code for the test cases was generated using jdk8 or earlier and the runtime jdk is also jdk8 or earlier, or if the source code for the test cases was generated using jdk9 later and the runtime jdk is also jdk9 or later.
2. Math.exp() operations where the expected result is `Infinity` are not executed if the runtime jdk is later than jdk8 and the platform is win_x86-32.  This is to avoid the known defect AdoptOpenJDK/openjdk-tests#2062 / AdoptOpenJDK/openjdk-support#182 pending a resolution.

With PR https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/378 the reported affected test targets MathLoadTest_all_0 and LockingLoadTest_0 all now pass.

Test runs across jdk8, jdk11 and jdk15 for hotspot and openj9:

jdk8

hotspot
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4863/
arm_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4864/
ppc64_aix: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4841/
ppc64le_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4842/
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4843/
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4844/
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4845/
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4846/
x86-32_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4847/

openj9
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4865/
ppc64_aix: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4850/
ppc64le_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4851/
ppc64le_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4857/
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4852/
s390x_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4858/
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4853/
x86-64_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4859/
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4854/
x86-64_mac_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4860/
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4855/
x86-64_windows_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4861/
x86-32_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4862/

jdk11

hotspot
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4874/
arm_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4890/
ppc64_aix: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4868/
ppc64le_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4869/
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4870/
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4871/
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4872/
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4873/
x86-32_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4891/ - fails with
16:43:11 LLT testFailure: testExp(net.adoptopenjdk.test.math.MathAPITest): exp(double)[21] :: expected: but was:<0.0>
16:43:11 LLT junit.framework.AssertionFailedError: exp(double)[21] :: expected: but was:<0.0>

openj9
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4804/
ppc64_aix: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4877/
ppc64le_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4878/
ppc64le_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4884/
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4879/
s390x_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4885/
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4880/
x86-64_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4886/
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4881/
x86-64_mac_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4892/
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4882/
x86-64_windows_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4888/

jdk15

hotspot
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4901/
arm_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4902/
ppc64_aix: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4895/
ppc64le_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4896/
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4897/
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4898/
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4899/
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4900/
x86-32_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4903/

openj9
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4918/
ppc64_aix: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4906/
ppc64le_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4907/
ppc64le_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4913/
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4908/
s390x_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4914/
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4909/
x86-64_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4915/
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4910/
x86-64_mac_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4916/
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4911/
x86-64_windows_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4917/

**Comment by lumpfish** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/378
