### ISSUE TITLE
git fetch openjdk-tests fails on aarch64

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-systemtest#404]
Problem:
The failure occurs right after we start performing sanity.system and extended.system tests on the aarch64 test node.
```
 > git fetch --tags --force --progress -- https://github.com/AdoptOpenJDK/openjdk-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/AdoptOpenJDK/openjdk-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: remote: Enumerating objects: 21, done.        
remote: Counting objects:   4% (1/21)        
etc etc    
remote: Counting objects: 100% (21/21), done.        
remote: Compressing objects:   4% (1/21)        
etc etc     
remote: Compressing objects: 100% (21/21), done.        
Receiving objects:   0% (1/11853)
etc etc
Receiving objects:  15% (1778/11853)
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

- test suite/name?
[JDK8 j9 extended.system](https://trss.adoptopenjdk.net/output/build?id=601b06c8ddf93e76e9feb424) - test-packet-ubuntu1604-armv8-1
[JDK8 j9 sanity.system](https://trss.adoptopenjdk.net/output/build?id=601b06c8ddf93e76e9feb425) - test-docker-ubuntu2004-armv8-1
JDK16 j9 sanity.system](https://trss.adoptopenjdk.net/output/build?id=601b904dddf93e76e9ff1013) - build-docker-ubuntu1804-armv8-2
JDK16 j9 sanity.system (xl)](https://trss.adoptopenjdk.net/output/build?id=601b903eddf93e76e9ff0ff0) - test-packet-ubuntu1604-armv8-1
[JDK16 j9 extended.system (xl)](https://trss.adoptopenjdk.net/output/build?id=601b903eddf93e76e9ff0fed) - test-docker-ubuntu2010-armv8-1
- Is there an existing issue elsewhere covering this?
Not that I found.
- Which machine(s) does it work on?
build-packet-ubuntu1804-armv8l-1f2
build-packet-ubuntu1804-armv8l-1a
test-packet-ubuntu1604-armv8-2
build-packet-ubuntu1804-armv8l-1c
build-packet-ubuntu1804-armv8l-1b
build-packet-ubuntu1804-armv8l-1a

- Which machine(s) does it fail on?
build-docker-ubuntu1804-armv8-2
test-docker-ubuntu2004-armv8-1
test-docker-ubuntu2010-armv8-1
test-packet-ubuntu1604-armv8-1
- Do you have a link to a Grinder re-run if the test with the failure?

Any other details:
In passing runs, we see the message "Avoid second fetch" after the git fetch command. 

Could be an infra problem based on the node names. May need to open secondary issue after further investigation.

**Comment by adamfarley** [comment]
Using grinders on two of the "failing" machines results in the same "Avoid second fetch" messages.

Rebuilding the pipeline job to rule out limitations with the grinder.

**Comment by adamfarley** [comment]
Git fetch appears to have passed.

Could this be a temporary issue? Unknown. Will put this on the backburner and review the nightlies tomorrow and Monday.

If the issue does not reoccur by Monday (8/2/2021), I'll close this issue.

**Comment by adamfarley** [comment]
Didn't even need to wait that long, here's a reproduction on [test-docker-ubuntu1804-armv8-1](https://trss.adoptopenjdk.net/output/build?id=601c612bddf93e76e9ffe9c1).

Investigation resumed.

**Comment by sxa** [comment]
A couple of things:
- This may be related to the issues we've seen on some builds on the ThunderX aarch64 systems (https://github.com/AdoptOpenJDK/openjdk-build/issues/1804#issuecomment-754592226)
- A number of the machines listed above have now been renamed: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1809#issuecomment-771658763

So the hosts that it


Which machine(s) does it work on?
build-packet-ubuntu1804-armv8l-1f2 (D05)
build-packet-ubuntu1804-armv8l-1a (D05)
test-packet-ubuntu1604-armv8-2 (?)
build-packet-ubuntu1804-armv8l-1c (D05)
build-packet-ubuntu1804-armv8l-1b (D05)
build-packet-ubuntu1804-armv8l-1a (D05)

Which machine(s) does it fail on?
build-docker-ubuntu1804-armv8-2 (Hosted on build-packet-ubuntu1804-armv8-1 - ThunderX)
test-docker-ubuntu2004-armv8-1 (ThunderX)
test-docker-ubuntu2010-armv8-1 (ThunderX)
test-packet-ubuntu1604-armv8-1 (ThunderX)

**Comment by adamfarley** [comment]
Closing this issue as the underlying issue appears to be ThunderX-specific, and the machines may now be disabled until they are removed.

Further actions on the underlying issue will take place in [this infra issue](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1897).
