### ISSUE TITLE
Add support for ARM platform

### ISSUE THREAD

**Issue by JamesKingdon** [AdoptOpenJDK/openjdk-systemtest#42]
Attempting to run the tests on arm fails with

> GEN stderr Caused by: net.adoptopenjdk.stf.StfException: Unknown architecture value: 'arm'. Expected one of '390|x86|ppc|x86'

**Comment by lumpfish** [comment]
Support needs to be added in STF.
Raised https://github.com/AdoptOpenJDK/stf/issues/16

**Comment by lumpfish** [comment]
PR submitted at https://github.com/AdoptOpenJDK/stf/pull/17

**Comment by lumpfish** [comment]
The STF PR has been merged.  I've run some of the openjdk-systemtest load tests on a Pi with IBM Java 8 32-bit which ran OK.

**Comment by karianna** [comment]
@lumpfish safe to close this then you think?  We can always open up new issues for specfic regressions?

**Comment by JamesKingdon** [comment]
Great! Many thanks.

**Comment by lumpfish** [comment]
@karianna - yes, closing
