### ISSUE TITLE
Enable ability to run all tests in a JCK test suite

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-systemtest#49]
Example: I want to run all of the DEVTOOLS suite. There doesn't appear to be a suitable target for this, or if there is it's not documented in the `make help.jck` output.

Suggest `make test.jck8b.runtime` or `make test.jck8b.runtime.all`.

**Comment by Mesbah-Alam** [comment]
Closing this issue as it seems obsolete now that we have [playlists](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/jck) for jck tests that are capable to run jck targets locally (using TKG) as well as by Jenkins jobs.
