### ISSUE TITLE
Enable openjdk-systemtest in AdoptOpenJDK Jenkins build

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#5]
**Steps**
1) Integrate openjdk-systemtest with the testKitGen, and be able to drive the systemtests via testKitGen generated makefiles.
2) Add Jenkins jobs for system tests in AdoptOpenJDK.

**Comment by smlambert** [comment]
Yes, this will allow us to group certain tests into a sanity group, versus an extended group and 'block' builds if a particular group fails.  It will also allow us to bring together and report on all of output from all of the various different types of tests.

**Comment by Mesbah-Alam** [comment]
System tests are running in Adopt Jenkins build. Closing this issue.
