### ISSUE TITLE
Mauve Load tests failing on ppc64le with UnknownHostException

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#66]
MauveSingleInvocationLoadTest and  MauveSingleThreadLoadTest are failing across all versions of Java on ppc64le platforms.

**Error**
> java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 14:58:09 LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 14:58:09 LT  	at java.base/java.lang.Thread.run(Thread.java:844)
> 14:58:09 LT  Caused by: java.net.UnknownHostException: test-ubuntu-16-04-1: Name or service not known
> 14:58:09 LT  	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
> 14:58:09 LT  	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:924)
> 14:58:09 LT  	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1504)
> 14:58:09 LT  	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:843)
> 14:58:09 LT  	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1494)
> 14:58:09 LT  	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1626)
> 14:58:09 LT  	... 11 more

**Build links:** 
1. openjdk9_hs_systemtest_ppc64le_linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_hs_systemtest_ppc64le_linux/1/
2.  openjdk8_hs_systemtest_ppc64le_linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_hs_systemtest_ppc64le_linux/1/
3. openjdk9_j9_systemtest_ppc64le_linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_j9_systemtest_ppc64le_linux/1/
4.openjdk8_j9_systemtest_ppc64le_linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_ppc64le_linux/1/

**Comment by sxa555** [comment]
The machine `test-osuosl-ppc64le-ubuntu-16.04-2` (as known to jenkins) calls itself `test-ubuntu-16-04-1` - there is no entry for this on the system's `/etc/hosts` which is almost certainly the issue here. https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/131 talks about similar issues elsewhere. I've fixed this on `test-osuosl-ppc64le-ubuntu-16.04-1` and `test-osuosl-ppc64le-ubuntu-16.04-2` for now which should fix it, but we need to sensible strategy for this going forward.

**Comment by Mesbah-Alam** [comment]
Thanks @sxa555 for fixing the issue in the two ppc64le test machines. The two Mauve tests are passing now in all the ppc64le builds: https://ci.adoptopenjdk.net/view/System%20tests/. 

I agree that we should have a sensible strategy going forward for this. Thanks also for leaving your comment regarding this in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/131. I will monitor that issue. 

I will close #66 at this point.
