### ISSUE TITLE
DirectByteBufferTest fails with NullPointerException on openjdk8_openj9 SDK

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#67]
DirectByteBufferTest fails with NullPointerException on openjdk8_openj9 SDKs on, at least, x64 and ppc64le linux platforms. It works fine on hotspot, as well as openjdk9_openj9 SDKs.

**Testcase**

The test creates a array of ByteBuffer of length = 90, and allocates a new bytebuffer of ALLOC_SIZE=10 MBytes in each index of that array (by calling ByteBuffer.allocateDirect(..)) and de-refences immediately to allow GC to happen. 
`public static void testDirectMemory() {
		try {
			int ITERATIONS = 90;
			int ALLOC_SIZE = 10000000; // 10Mbytes

			ByteBuffer[] bbStore = new ByteBuffer[ITERATIONS];
			Runtime r = Runtime.getRuntime();

			System.out.println("Total memory is: " + r.totalMemory());
			System.out.println("Initial free memory: " + r.freeMemory());
			int i;
			for (i = 0; i < ITERATIONS; i++) {

				System.out.println("Iteration: " + i + " Total memory is: "
						+ r.totalMemory() + "Initial free memory: "
						+ r.freeMemory());
				bbStore[i] = ByteBuffer.allocateDirect(ALLOC_SIZE);
				// *** dereference to allow GC
				bbStore[i] = null;
			}
			
			assertTrue(i==ITERATIONS);
			
		} catch (Exception e) {
			System.out.println("Caught Exception: \n" + e);
			fail("Exception::"+e);
		}
	}`

**Error stacktrace** 
> 14:32:27 DBLT Caught Exception: 
> 14:32:27 DBLT java.lang.NullPointerException
> 14:32:27 DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Exception::java.lang.NullPointerException
> 14:32:27 DBLT junit.framework.AssertionFailedError: Exception::java.lang.NullPointerException
> 14:32:27 DBLT 	at junit.framework.Assert.fail(Assert.java:57)
> 14:32:27 DBLT 	at junit.framework.TestCase.fail(TestCase.java:227)
> 14:32:27 DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:49)
> 14:32:27 DBLT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 14:32:27 DBLT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 14:32:27 DBLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 14:32:27 DBLT 	at java.lang.reflect.Method.invoke(Method.java:498)
> 14:32:27 DBLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
> 14:32:27 DBLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
> 14:32:27 DBLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
> 14:32:27 DBLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
> 14:32:27 DBLT 	at junit.framework.TestResult.run(TestResult.java:125)
> 14:32:27 DBLT 	at junit.framework.TestCase.run(TestCase.java:129)
> 14:32:27 DBLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
> 14:32:27 DBLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
> 14:32:27 DBLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
> 14:32:27 DBLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
> 14:32:27 DBLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 14:32:27 DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 14:32:27 DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
> 14:32:27 DBLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
> 14:32:27 DBLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
> 14:32:27 DBLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 14:32:27 DBLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 14:32:27 DBLT 	at java.lang.Thread.run(Thread.java:811)
> 14:32:27 DBLT testFinished: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest)

**Build**
1) openjdk8_j9_systemtest_x86-64_linux : https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_x86-64_linux/5/
2) openjdk8_j9_systemtest_ppc64le_linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_ppc64le_linux/3/

**Comment by dmitripivkine** [comment]
I guess NULL has been returned because of lack of Native memory, so too many DBB objects were not cleared at the moment. Native memory should be released from DBB object at Finalization time. This job should be done by Finalization threads. Finalization threads run with lowest priority, so if test thread generates DBB objects aggressively and there is not enough resources in Environment to run Finalization threads with performance high enough an accumulation of objects possible in the queue.
This is a common problem for JVMs. Hotspot and openj9 have different implementations so the dynamic balance on machine to pass/fail this test is slightly different.
The general problem here is a lack of control of Finalizaton work. To address this the new API is introduced in Java 9. It allows test thread to wait until all objects in the queue are processed

**Comment by Mesbah-Alam** [comment]
@dmitripivkine , thanks for looking into it. 

FYI.. I *could not* reproduce the same issue using the latest IBM Java 8 SR5 

SDK used : 
`java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 8.0.5.0 - pxa6480sr5-20170905_01(SR5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20170901_363591 (JIT enabled, AOT enabled)
J9VM - d56eb84
JIT  - tr.open_20170901_140853_d56eb84
OMR  - b033a01)
JCL - 20170823_01 based on Oracle jdk8u144-b01`

Command line used to reproduce using IBM Java 8 SR5:
`$JAVA_HOME/bin/java -classpath /team/mesbaha/openjdk-systemtest-issue/67/stf/stf.load/bin:/team/mesbaha/openjdk-systemtest-issue/67/stf/stf.core/bin:/team/mesbaha/openjdk-systemtest-issue/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/team/mesbaha/openjdk-systemtest-issue/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/team/mesbaha/openjdk-systemtest-issue/systemtest_prereqs/junit-4.12/junit-4.12.jar:/team/mesbaha/openjdk-systemtest-issue/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/team/mesbaha/openjdk-systemtest-issue/67/openjdk-systemtest/openjdk.test.nio/bin/lib/filesystem.jar:/team/mesbaha/openjdk-systemtest-issue/67/openjdk-systemtest/openjdk.test.gc/bin:/team/mesbaha/openjdk-systemtest-issue/67/openjdk-systemtest/openjdk.test.nio/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /team/mesbaha/openjdk-systemtest-issue/67/results -resultsPrefix 1.DBLT. -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.DirectByteBuffer.threadCount 3 -suite.DirectByteBuffer.totalNumberTests 16 -suite.DirectByteBuffer.inventoryFile /team/mesbaha/openjdk-systemtest-issue/67/results/1.DBLT.inventory/openjdk.test.load/config/inventories/gc/directByteBuffer.xml -suite.DirectByteBuffer.inventoryExcludeFile none -suite.DirectByteBuffer.selection random -suite.DirectByteBuffer.seed -1 -suite.DirectByteBuffer.repeatCount 1 -suite.DirectByteBuffer.thinkingTime 0ms..0ms
`

**Comment by Mesbah-Alam** [comment]
@dmitripivkine, Thanks for looking into it. 

Fyi... I could not reproduce the same issue using IBM Java 8 SR5 

Java SDK version tried : 

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pxa6480sr6-20171229_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180117_376307 (JIT enabled, AOT enabled)
OpenJ9   - b338003
OMR      - 3cda7d8
IBM      - 2321a81)
JCL - 20171113_01 based on Oracle jdk8u151-b12

**Comment by pshipton** [comment]
OpenJ9 issue eclipse/openj9#1077 was opened, and now resolved to fix this problem.
