### ISSUE TITLE
HCRLateAttach throwing AgentInitializationException on Java9

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-systemtest#7]
Issue shows on both the HotSpot builds and OpenJ9 across all architectures. Issue is in the `asm` dependency which currently has a beta version 6 that still shows an issue. Further investigation required and to monitor the asm project for a full v6 release

```
LT  stderr Caused by: java.lang.IllegalArgumentException
LT  stderr      at org.objectweb.asm.ClassReader.<init>(Unknown Source)
LT  stderr      at org.objectweb.asm.ClassReader.<init>(Unknown Source)
LT  stderr      at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:70)
LT  stderr      ... 6 more
LT  stderr Agent failed to start!
LT  stderr JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
LT  19:28:18.488 - Parsing inventory file. Root=/tmp/stf/20170916-192804-HCRLateAttachWorkload/results/1.LT.inventory File=openjdk.test.load/config/inventories/util/util.xml
AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
AG  stderr      at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(jdk.attach@9-internal/OpenJ9VirtualMachine.java:324)
AG  stderr      at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(jdk.attach@9-internal/OpenJ9VirtualMachine.java:229)
AG  stderr      at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
STF 19:28:18.500 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)
```

**Comment by Mesbah-Alam** [comment]
Test is enabled on JDK8 only, as it keeps failing on JDK11 due to outdated ASM which doesn't understand JDK11 : https://github.com/AdoptOpenJDK/openjdk-tests/pull/1009

**Comment by smlambert** [comment]
So, presumably still to do is to update this test to pull and use a newer ASM jar for 11+ ?

**Comment by adamfarley** [comment]
Will set up the test mats locally and give things a whirl with the newer asm, making sure the tests still work on the various jdks.

**Comment by adamfarley** [comment]
Update: Had difficulty running the tests locally, but was able to execute in the end.

ASM version 7.0 produces a different error for jdk11, and version 7.1 tells me to use version 7. 

Had a few ideas overnight. Will try them now, and update when I have more information.

**Comment by adamfarley** [comment]
Update: Nothing I've tried has worked, and when I Build+run on jdk11 with asm7, the test still fails with an error, and insists I should be using asm7.

Still digging.

**Comment by adamfarley** [comment]
The problem was that the test was still using Opcodes from ASM 5. This has been resolved in my sandbox, and the test now runs and passes on jdk11 on openj9.

I need to:
- Test on 11-Hotspot and 8-OpenJ9
- If needed: configure the build and test execution files to use asm 7 for 11+, and asm 5.2 for jdk8.
- Tidy up the commits & commit the test fix.
- Re-introduce the test into the test pool.

**Comment by adamfarley** [comment]
All done. Closing issue.
