### ISSUE TITLE
Add support for arm platforms (32 and 64 bit)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-systemtest#73]
Failing to compile due to unrecognized platform:  aarch64

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk9_test_arm64_linux/10/console

18:07:41 /home/jenkins/workspace/openjdk9_test_arm64_linux/openjdk-test/TestConfig/scripts/build_test.xml:75: The following error occurred while executing this line:
18:07:41 /home/jenkins/workspace/openjdk9_test_arm64_linux/openjdk-test/systemtest/build.xml:73: The following error occurred while executing this line:
18:07:41 /home/jenkins/workspace/openjdk9_test_arm64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:64: The following error occurred while executing this line:
18:07:41 /home/jenkins/workspace/openjdk9_test_arm64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:460: The following error occurred while executing this line:
18:07:41 /home/jenkins/workspace/openjdk9_test_arm64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:551: java os.arch property value aarch64 not recognised.  Update the get-platform-arch macrodef in openjdk.build/include/top.xml
18:07:41

**Comment by Mesbah-Alam** [comment]
Interesting.. We do have a condition for aarch64 in macrodef get-platform-arch in openjdk.build/top.xml 
```
<condition property="@{property}" value="arm">
				<and>
					<contains string="@{arch}" substring="aarch64"/>
				</and>
			</condition>
```
Need to investigate why it's not matching.

**Comment by smlambert** [comment]
21:08:18 build-natives-unix:
21:08:18      [exec] make[1]: Entering directory '/home/jenkins/workspace/openjdk11_hs_systemtest_aarch64_linux/openjdk-tests/systemtest/openjdk-systemtest/openjdk.test.modularity/src/tests/com.test.jlink/native'
21:08:18      [exec] make[1]: Leaving directory '/home/jenkins/workspace/openjdk11_hs_systemtest_aarch64_linux/openjdk-tests/systemtest/openjdk-systemtest/openjdk.test.modularity/src/tests/com.test.jlink/native'
21:08:18      [exec] makefile:68: *** "The variable PLATFORM=linux_arm-64 is not one of osx_x86-64,aix_ppc-32,aix_ppc-64,linux_390-31,linux_390-64,linux_ppc-32,linux_ppc-64,linux_x86-32,linux_x86-64,win_x86-32,win_x86-64,zos_390-31,zos_390-64,linux_ppcle-64,linux_arm-32".  Stop.

**Comment by smlambert** [comment]
This is causing systemtests to [fail compilation on aarch64](https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_aarch64_linux/104/console).  

@lumpfish - please comment and/or offer a fix.

**Comment by lumpfish** [comment]
PR submitted: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/224

I can't see a way to build and run the tests from my fork https://github.com/lumpfish/openjdk-systemtest  via a job at https://ci.adoptopenjdk.net/ and I don't have access locally to a linux_arm-64 machine.

The makefile had no specific settings for CFLAGS and LFLAGS for linux_arm-32 either, so that platform was running with the default settings.  I added stanzas for both linux_arm-32 and linux_arm-64 to be explicit.

**Comment by smlambert** [comment]
At present, to test via Grinder, you have to change the [clone_systemtest target in systemtest/common.xml](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/systemtest/common.xml#L62-L69) file in your openjdk-tests branch:

`<target name="clone_stf">
		<echo message="clone stf from lumpfish -b add_arm_to_native_build" />
		<exec executable="git" failonerror="false" dir="${SYSTEMTEST_ROOT}">
			<arg value="clone" />
			<arg value="-b" />
			<arg value="add_arm_to_native_build" />
			<arg value="--depth" />
			<arg value="1" />
			<arg value="--single-branch" />
			<arg value="${git-prefix}://github.com/lumpfish/stf.git" />
		</exec>`

**Comment by lumpfish** [comment]
Thanks.  Test run at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1049/consoleFull.  There are some failures, but they're related to certain -X options being passed into some of the tests.

**Comment by smlambert** [comment]
Thanks @lumpfish !
