### ISSUE TITLE
LockingLoadTest fails on hotspot VMs

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#76]
LockingLoadTest fails on openjdk8_hs_systemtest_x86-64_linux with error: 

```
 LLT testFailure: testPow(net.adoptopenjdk.test.math.MathAPITest): pow(double)[5] :: expected:<8.382703296667981E-131> but was:<8.382703296667982E-131>
        LLT junit.framework.AssertionFailedError: pow(double)[5] :: expected:<8.382703296667981E-131> but was:<8.382703296667982E-131>
        LL
```
**Build link**
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_hs_systemtest_x86-64_linux/lastSuccessfulBuild/artifact/openjdk-tests/TestConfig/test_output_15187805588474/TestTargetResult.tap/*view*/

**Comment by Mesbah-Alam** [comment]
We need to update the test case to accept the failing value as we did for math load test .

**Comment by Mesbah-Alam** [comment]
Another failure: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_hs_systemtest_x86-64_linux/lastSuccessfulBuild/artifact/openjdk-tests/TestConfig/test_output_15194073641611/TestTargetResult.tap/*view*/

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/77

**Comment by Mesbah-Alam** [comment]
We have a similar failure in LockingLoadTest in the /openjdk10_hs_systemtest_x86-64_linux build : https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/21/console.

``` LLT testFailure: testToRadians(net.adoptopenjdk.test.math.MathAPITest): toRadians(double)[0] :: expected:<-1.5687832071922932E304> but was:<-1.5687832071922935E304>
        LLT junit.framework.AssertionFailedError: toRadians(double)[0] :: expected:<-1.5687832071922932E304> but was:<-1.5687832071922935E304>
        L
```

**Comment by Mesbah-Alam** [comment]
This creates a concern about the MathAPITest in general. We are seeing failures popping up with mismatches between Oracle and IBM results in some of these Math APIs, and we are fixing them according to the decision made originally in https://github.com/eclipse/openj9/issues/1001#issuecomment-362041853. 

It is fine with me adding in these fixes where we accept both IBM and Oracle values for the case where the difference is within 1 ulp. However, we need to make some more substantial test changes if this continues to happen in future.

**Comment by smlambert** [comment]
Yes, I think you may want to create an issue to proactively look at the MathAPITest to see which other asserts/locations in code may be same scenario.

**Comment by Mesbah-Alam** [comment]
double(1) test fails on openjdk10, this is a new failure: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/23/console

Testing the fix in my branch : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/332/console

**Comment by Mesbah-Alam** [comment]
All adjustments have been made to all the failing tests. The tests are stable now. This issue can now be closed.
