### ISSUE TITLE
java.lang.IllegalArgumentException: Constant pool index out of bounds

### ISSUE THREAD

**Issue by Ingo60** [AdoptOpenJDK/openjdk-systemtest#95]
When there are a lot of custom annotations on a class, and later you want to read the annotations from the class file, the following happens (Open J9 JDK9, JDK10, linux x64):

    java.lang.IllegalArgumentException: Constant pool index out of bounds
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(java.base@10-adoptopenjdk/AnnotationParser.java:77)
	at java.lang.Class.getAnnotationCache(java.base@10-adoptopenjdk/Class.java:2646)
	at java.lang.Class.getAnnotation(java.base@10-adoptopenjdk/Class.java:2294)

I'd provide an example if needed (this would be quite a bit of work though, since the annotations are compiler generated), however, I'm not even sure this is the right place to post this.

This used to work in Open j9 jdk8.

**Comment by smlambert** [comment]
Thanks @Ingo60 - sounds like a potential openj9 defect.  I have created an issue at the openj9 project, as I think that is the right place to report it: https://github.com/eclipse/openj9/issues/1588

If you could add a comment to that issue (openj9/1588), as to whether you have run the test case using the openjdk9/openjdk10 builds (versus the openjdk9-openj9 and openjdk10-openj9 builds).
