### ISSUE TITLE
mauve tests setSelectionInterval and setSelectionMode fail on jdk10 + jdk11

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-systemtest#97]
Mauve tests gnu.testlet.javax.swing.DefaultListSelectionModel.setSelectionInterval and gnu.testlet.javax.swing.DefaultListSelectionMode fail on jdk10 but pass on jdk8 and jdk9.

This may be because of a tightening of the specification when switching from a less restrictive mode to a more restrictive mode - see https://bugs.openjdk.java.net/browse/JDK-8191436.  This issue is to investigate whether that is indeed the cause, and if so, exclude the tests from the mauve workloads, otherwise raise a bug report against openjdk.

The test is run as part of the SingleInvocationMauveTest and SingleThreadMauveTest load test workloads.

To view, run or change the individual test cases:

1. Build the openjdk-systemtest repository.  The make configure step will download and build the mauve test cases under a systemtest_prereqs directory

2. 
- unzip the systemtest_prereqs/mauve/mauve.jar file
-  edit the test case
- javac individual test cases - e.g.
cd /home/user/systemtest_prereqs/mauve//gnu/testlet/javax/swing/DefaultListSelectionModel
javac -cp /home/user/systemtest_prereqs/mauve setSelectionInterval.java

**Comment by Mesbah-Alam** [comment]
Same failures seen on latest jdk11: 

```
LT  FAIL: gnu.testlet.javax.swing.DefaultListSelectionModel.setSelectionInterval: SINGLE_SELECTION_X (number 7)
LT  got 2 but expected 4
```
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/362/tapResults/

**Comment by lumpfish** [comment]
I have confirmed that the fix for https://bugs.openjdk.java.net/browse/JDK-8191436 caused this behavior change so the tests should remain excluded.
